### ISSUE TITLE
Invalid drawable tag vector on pre Lollipop

### ISSUE THREAD

**Issue by palatin** [gauravk95/bubble-navigation#12]
```
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_artist.xml from drawable resource ID #0x7f0700b8
        at android.content.res.Resources.loadDrawable(Resources.java:2842)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
        at com.gauravk.bubblenavigation.BubbleToggleView.init(BubbleToggleView.java:118)
        at com.gauravk.bubblenavigation.BubbleToggleView.<init>(BubbleToggleView.java:71)
     Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:917)
        at android.graphics.drawable.Drawable.createFromXml(Drawable.java:858)
        at android.content.res.Resources.loadDrawable(Resources.java:2839)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:602) 
        at com.gauravk.bubblenavigation.BubbleToggleView.init(BubbleToggleView.java:118) 
        at com.gauravk.bubblenavigation.BubbleToggleView.<init>(BubbleToggleView.java:71) 
```

maybe `VectorDrawableCompat.create()` shoud fix it?

**Comment by gauravk95** [comment]
Thanks for reporting this! I will look into it ASAP.
Yeah, I guess `VectorDrawableCompat.create()` should help.
